/*Comparar (x>=y) and (x<=z) vs. BETWEEN */
SELECT *
	FROM PRESTAMOS
    WHERE PREIMPORTE <= 9000
    AND PREIMPORTE >= 1000;

SELECT *
	FROM PRESTAMOS
    WHERE PREIMPORTE BETWEEN 1000 AND 9000;

/* Analizar <Condición> AND TAUTOLOGIA */
SELECT *
	FROM DEBE
    WHERE CLINOMBRE LIKE 'A%' AND 2=2;

/* Analizar <Condición> OR TAUTOLOGIA */
SELECT *
	FROM DEBE
    WHERE CLINOMBRE LIKE 'A%' OR 2=2;

/* Analizar <Condición> AND FALASIA */
SELECT *
	FROM DEBE
    WHERE CLINOMBRE LIKE 'A%' AND 1=2;

/* Analizar <Condición> OR FALASIA */
SELECT *
	FROM DEBE
    WHERE CLINOMBRE
 LIKE 'A%' OR 1=2;